// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjC7fAdIHA6db1n0R9TIjJeV9BusLE20',
    appId: '1:128257096922:web:ab0d05f52288574ed539e3',
    messagingSenderId: '128257096922',
    projectId: 'employee-app-40e35',
    authDomain: 'employee-app-40e35.firebaseapp.com',
    databaseURL: 'https://employee-app-40e35-default-rtdb.firebaseio.com',
    storageBucket: 'employee-app-40e35.appspot.com',
    measurementId: 'G-XTP0KCRMWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMHai99ya-HShSvXNBs2rP2L0bydyydx0',
    appId: '1:128257096922:android:d3a75bec04f9a0bdd539e3',
    messagingSenderId: '128257096922',
    projectId: 'employee-app-40e35',
    databaseURL: 'https://employee-app-40e35-default-rtdb.firebaseio.com',
    storageBucket: 'employee-app-40e35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBtSIscWkGWLw-ggDaUU99EFFHQlcCoU',
    appId: '1:128257096922:ios:35c3db8f11fbf5b1d539e3',
    messagingSenderId: '128257096922',
    projectId: 'employee-app-40e35',
    databaseURL: 'https://employee-app-40e35-default-rtdb.firebaseio.com',
    storageBucket: 'employee-app-40e35.appspot.com',
    iosBundleId: 'com.example.sharesep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTBtSIscWkGWLw-ggDaUU99EFFHQlcCoU',
    appId: '1:128257096922:ios:35c3db8f11fbf5b1d539e3',
    messagingSenderId: '128257096922',
    projectId: 'employee-app-40e35',
    databaseURL: 'https://employee-app-40e35-default-rtdb.firebaseio.com',
    storageBucket: 'employee-app-40e35.appspot.com',
    iosBundleId: 'com.example.sharesep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqjC7fAdIHA6db1n0R9TIjJeV9BusLE20',
    appId: '1:128257096922:web:16a3bfe1ece8ede9d539e3',
    messagingSenderId: '128257096922',
    projectId: 'employee-app-40e35',
    authDomain: 'employee-app-40e35.firebaseapp.com',
    databaseURL: 'https://employee-app-40e35-default-rtdb.firebaseio.com',
    storageBucket: 'employee-app-40e35.appspot.com',
    measurementId: 'G-CQ0JQGMW23',
  );

}