// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOMkLVmbQXtQN7XQlfuztijKPqaDGZ5Cc',
    appId: '1:702561533951:web:be843ce753ccd516a771ca',
    messagingSenderId: '702561533951',
    projectId: 'sharesep1-db',
    authDomain: 'sharesep1-db.firebaseapp.com',
    databaseURL: 'https://sharesep1-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep1-db.appspot.com',
    measurementId: 'G-EL2F7L430L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAoSFt41K9-qYAwrnOHS9TwS-NvUyDiSE',
    appId: '1:702561533951:android:66767df79f9a2738a771ca',
    messagingSenderId: '702561533951',
    projectId: 'sharesep1-db',
    databaseURL: 'https://sharesep1-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep1-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBznWizc3PxZwhuSHCfZOLivX-PBQQk0NY',
    appId: '1:702561533951:ios:25d19b7e193c1d45a771ca',
    messagingSenderId: '702561533951',
    projectId: 'sharesep1-db',
    databaseURL: 'https://sharesep1-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep1-db.appspot.com',
    iosClientId: '702561533951-fn2fdagv5fm1ulir72uqd4hs3eel93gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharesep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBznWizc3PxZwhuSHCfZOLivX-PBQQk0NY',
    appId: '1:702561533951:ios:ac22753c25ad8659a771ca',
    messagingSenderId: '702561533951',
    projectId: 'sharesep1-db',
    databaseURL: 'https://sharesep1-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep1-db.appspot.com',
    iosClientId: '702561533951-n96anf8nusg977rhc6kjefdgdro7btgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharesep.RunnerTests',
  );
}
