// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_iZwhUPZLt8PRWlIubU147rLUDMLpotc',
    appId: '1:998685434592:web:0367000a2364ac807be685',
    messagingSenderId: '998685434592',
    projectId: 'sharesep-db',
    authDomain: 'sharesep-db.firebaseapp.com',
    databaseURL: 'https://sharesep-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep-db.appspot.com',
    measurementId: 'G-142XEPCMSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGk2ap-Ee1xSzE9rRMdFKHtOEa3hdEltI',
    appId: '1:998685434592:android:9b99f133beacd6677be685',
    messagingSenderId: '998685434592',
    projectId: 'sharesep-db',
    databaseURL: 'https://sharesep-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZFKl0GZr6UrhV9yQKCkazQFh_bS1Oyw',
    appId: '1:998685434592:ios:4ae32952166b81a17be685',
    messagingSenderId: '998685434592',
    projectId: 'sharesep-db',
    databaseURL: 'https://sharesep-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep-db.appspot.com',
    iosBundleId: 'com.example.sharesep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZFKl0GZr6UrhV9yQKCkazQFh_bS1Oyw',
    appId: '1:998685434592:ios:e0fc385a97795e737be685',
    messagingSenderId: '998685434592',
    projectId: 'sharesep-db',
    databaseURL: 'https://sharesep-db-default-rtdb.firebaseio.com',
    storageBucket: 'sharesep-db.appspot.com',
    iosBundleId: 'com.example.sharesep.RunnerTests',
  );
}
